### PR TITLE
Remove the title field from the form

### PR DESCRIPTION
**Pull request by karenroldan**
#### What Does This PR Add/Change?

Deleted the Title field. Context: pciE2j-1VQ-p2#comment-1674

Screenshot 2023-03-31 at 10 52 02

**Key changes:**

1. Updated all names from `Type and Title` to `Type` only. 
2. Updated the tests to reflect the name changes. 
3. Updated the tests to verify `Type` only. 

#### Testing Instructions

I've manually tested the changes and updated the tests! 

* Verify that the title field is no longer available in the form 
* The tests should be passed by running `yarn test` 

#### Issues

Related to #  
Closes #

### CODE REVIEW

**Comment by dpasque** [comment]
@karenroldan -- this looks great, thank you so much! 😄 This kind of PRs can be the worst because it is so many small updates! I really appreciate it 🙇 

Overall, the changes look great!

As I'm looking at this, I wonder if we should keep the issue title in the redux state and URL tracking (and pass it along to GitHub links) even though we remove it from all the places in the UI?

I feel like that could open up some cool potential use cases in the future, where maybe we seed the issue title with their most recent duplicate search phrase. Or we could do integrations like making a link in HappyChat that seeds Bugomattic with an issue title? Or really anything like that. 

What do you think @karenroldan and @john-legg?

**Comment by dpasque** [comment]
Also, one tiny adjustment - comparing to the mockups, I wonder if we should drop the margin a little bit on the Type fieldset?

```css
.typeFieldset {
	border: none;
	margin: 0 0 2.5rem 0;
	padding: 0;
}
```

From playing around, I think dropping the bottom margin ☝️  there to `1rem` looked a little more like the mockups. Does that sound right @john-legg?

**Comment by karenroldan** [comment]
> I feel like that could open up some cool potential use cases in the future, where maybe we seed the issue title with their most recent duplicate search phrase. Or we could do integrations like making a link in HappyChat that seeds Bugomattic with an issue title? Or really anything like that.

I think that's a good idea! It's always better to have it available so we can extend the functionality! I'll put those back. 👍🏻

**Comment by karenroldan** [comment]
All good! 

I've added back the issue title in the redux state and URL tracking! The fix can be found here: [519ea51](https://github.com/Automattic/bugomattic/pull/52/commits/519ea510d3311f24e0331b0b429a2726be0a68fa)

I've also updated the bottom margin from 2.5rem to 1rem. The fix can be found here: [ac56216](https://github.com/Automattic/bugomattic/pull/52/commits/ac5621611ad4490db456fd68a76e0a78a2a4b145)

/cc: @john-legg @dpasque

**Comment by dpasque** [comment]
@karenroldan -- thank you so much for the updates, they look awesome! 😄 

When I was running/looking at the unit tests locally, I noticed a couple had type warnings for the missing `issueTitle` so I just added those back in real quick in [511ebcc](https://github.com/Automattic/bugomattic/pull/52/commits/511ebcc96932ee0bc78a37c90a1b5078c063e85a) - I hope that's okay! 🙇

**Review by dpasque — APPROVED** [review]
This looks fantastic -- thank you again for knocking this out, and for being flexible with the state change! 😄 

Merge whenevs 😁 🚀

**Review by john-legg — APPROVED** [review]
Sorry for jumping in late! Looks good to me as well. Nicely done, Karen and Dan 🎉

**Comment by karenroldan** [comment]
> When I was running/looking at the unit tests locally, I noticed a couple had type warnings for the missing issueTitle so I just added those back in real quick in [511ebcc](https://github.com/Automattic/bugomattic/pull/52/commits/511ebcc96932ee0bc78a37c90a1b5078c063e85a) - I hope that's okay! 🙇

Thanks a lot, @dpasque! I don't see the warnings when running the unit tests locally. 😞 I run using `yarn test` and pressed `a` to run all tests. Do I need to set something else? 

I'll go ahead and merge this. Thanks for reviewing, John and Dan!

**Pull request merged**
